### ISSUE TITLE
In progress does not show on Backup Archives page

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-backup#164]
Please see gif - https://drive.google.com/file/d/1TWdmgHpBTkkIJ4rLQYZUQ7CptBPCvE8P/view?usp=sharing

**Comment by bwmarkle** [comment]
It's probably related to this issue to - https://drive.google.com/file/d/1dM4szMsE43fu9ztYYYR-nJct-yjj99-Z/view?usp=sharing

"Update protection" UI really isn't working.

**Comment by cssjoe** [comment]
I could not replicate the issue (on wpbex2 or CWP).

**Comment by nicolepaschen** [comment]
Also could not replicate
