### ISSUE TITLE
Notice still says BoldGrid Backup

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-backup#176]
I know there's a few variations of this based on user actions, please check them all. Sorry I missed before.
![notice-says-boldgrid-backup](https://user-images.githubusercontent.com/20601160/70105555-20de9500-160f-11ea-8106-a652b4ce4de9.PNG)

**Comment by bwmarkle** [comment]
Closing ticket. Doesn't appear to be an issue any longer.

![image](https://user-images.githubusercontent.com/5925563/71182144-8c497900-2243-11ea-9106-fd7dedde2c7e.png)
