### ISSUE TITLE
WP Security blocks certain js files from loading

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-backup#182]
![image](https://user-images.githubusercontent.com/5925563/70831779-6cd4cb00-1dc1-11ea-8de3-cc8dcd2d15a3.png)

**Comment by bwmarkle** [comment]
Either need to test and rename the file, or, figure out a way to bypass

**Comment by bwmarkle** [comment]
@jamesros161 I'm trying to replicate the initial problem, but I can't... Were you able to replicate the problem?

**Comment by jamesros161** [comment]
Yes. The initial problem was replicated by enabling the setting "Advanced Character String Filter".

This is found under the WP Security > Firewall > Additional Firewall Rules section
