### ISSUE TITLE
Error installing boldgrid backup premium - Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-backup#203]
```
Array
(
    [type] => 1
    [message] => Maximum execution time of 30 seconds exceeded
    [file] => /home/user/public_html/wp-admin/includes/class-wp-filesystem-direct.php
    [line] => 66
)
```

**Comment by bwmarkle** [comment]
Maybe...

```
if ( uploading_plugin && 'total upkeep premium' === $plugin ) {
    set_time_limit( 0 );
}
```

Another solution is to reduce the filesize of the total upkeep plugin.

**Comment by bwmarkle** [comment]
**Info on deleting folders...**

https://stackoverflow.com/questions/48214056/google-php-api-too-many-files
> By default the Google/Service directory contains all the code needed to access every Google Discovery services API. You don't technically need all of the files. You can safely delete everything under Google/Service that you don't need. Dont delete files from any of the other directories. Just remove the unneeded APIs.


https://stackoverflow.com/questions/60149830/google-api-php-client-10000-files-cant-upload-to-app-engine-service?noredirect=1&lq=1
> You may delete folders from services you don't intend to use in the following top folder

**Comment by bwmarkle** [comment]
And this one: https://github.com/googleapis/google-api-php-client/issues/1418

**Comment by bwmarkle** [comment]
Directory sizes:

```
boldgrid-backup-premium/vendor(issue-211)$ du -h -d1
624K    ./monolog
56K     ./firebase
1.4M    ./phpseclib
4.1M    ./guzzle
88K     ./composer
1.5M    ./guzzlehttp
14M     ./aws
216K    ./psr
380K    ./react
180K    ./symfony
28K     ./ralouphie
49M     ./google
71M     .
```


If we delete all the libraries except for the ones that start with **Drive**:
`boldgrid-backup-premium/vendor/google/apiclient-services/src/Google/Service$ ls -1 |grep -v '^Drive' | xargs rm -rf`

```
boldgrid-backup-premium/vendor(issue-211)$ du -h -d1
624K    ./monolog
56K     ./firebase
1.4M    ./phpseclib
4.1M    ./guzzle
88K     ./composer
1.5M    ./guzzlehttp
14M     ./aws
216K    ./psr
380K    ./react
180K    ./symfony
28K     ./ralouphie
1.3M    ./google
24M
```

What do you think @cssjoe

**Comment by cssjoe** [comment]
We can add the following to the build command string:
`find vendor/google/apiclient-services/src/Google/Service/ -mindepth 1 -maxdepth 1 \( ! -name "Drive*" ! -name "Drive*\.php" \) -exec rm -rf {} +`

**Comment by bwmarkle** [comment]
Fixed. Closing issue.
