### ISSUE TITLE
Fatal error when installing plugin through inspirations

### ISSUE THREAD

**Issue by rramo012** [BoldGrid/boldgrid-backup#225]
PHP Fatal error:  Uncaught Error: Class 'Boldgrid\\Library\\Library\\Plugin\\Notices' not found in /home/tria501x6522/public_html/wp-content/plugins/boldgrid-backup/includes/class-boldgrid-backup.php:553\nStack trace:\n#0 /home/tria501x6522/public_html/wp-content/plugins/boldgrid-backup/includes/class-boldgrid-backup.php(72): Boldgrid_Backup->define_admin_hooks()\n#1 /home/tria501x6522/public_html/wp-content/plugins/boldgrid-backup/boldgrid-backup.php(81): Boldgrid_Backup->__construct()\n#2 /home/tria501x6522/public_html/wp-content/plugins/boldgrid-backup/boldgrid-backup.php(142): run_boldgrid_backup()\n#3 /home/tria501x6522/public_html/wp-admin/includes/plugin.php(650): include_once('/home/tria501x6...')\n#4 /home/tria501x6522/public_html/wp-content/plugins/boldgrid-inspirations/includes/class-boldgrid-inspirations-deploy.php(1857): activate_plugin('boldgrid-backup...')\n#5 /home/tria501x6522/public_html/wp-content/plugins/boldgrid-inspirations/includes/class-boldgrid-inspirations-deploy.php(1651): Boldgrid_Inspirations_Deploy->download in /home/tria501x6522/public_html/wp-content/plugins/boldgrid-backup/includes/class-boldgrid-backup.php on line 553, referer: https://demo-dev.boldgrid.com/trial-4vu1217y/wp-admin/admin.php?page=boldgrid-inspirations

**Comment by bwmarkle** [comment]
FYI, it does appear the correct library versions are being installed.

![image](https://user-images.githubusercontent.com/5925563/75039068-dccc9500-5485-11ea-92aa-a10f661bb02b.png)

**Comment by bwmarkle** [comment]
Deploy, tested, good to go.
