### ISSUE TITLE
Fatal- AWS Client Conflicts with W3 Total Cache CDN

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-backup#266]
**Describe the bug**
If a user is using W3 Total Cache with AWS CDN and Total Upkeep AWS backup storage, a fatal error occurs: 
`[15-May-2020 15:14:40 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Aws\Common\Client\AbstractClient::__construct() must be an instance of Aws\Common\Credentials\CredentialsInterface, array given, called in /var/www/wordpress/html/wp-content/plugins/w3-total-cache/CdnEngine_CloudFront.php on line 40 and defined in /var/www/wordpress/html/wp-content/plugins/boldgrid-backup-premium/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php:73`

**To Reproduce**
1. Configure W3TC with AWS CDN
2. Configure Total Upkeep with AWS S3 Storage
3. Fatal error occurs

**Expected behavior**
If possible, the AWS client should be namespaced or otherwise protected from conflicting with other plugins that use the AWS client interface.

**Additional context**
A similar error occurred to another user using W3TC alongside another S3 plugin, if a fix can be found it should also be added to W3TC
`[08-May-2020 18:35:33 UTC] PHP Fatal error: Cannot redeclare Aws\constantly() (previously declared in /var/www/(snip)/wp-content/plugins/s3-media-maestro/vendor/aws/aws-sdk-php/src/functions.php:19) in /var/www/(snip)/wp-content/plugins/w3-total-cache/lib/Aws/Aws/functions.php on line 22`

**Comment by bwmarkle** [comment]
Just an FYI, I have been able to replicate this issue.
![image](https://user-images.githubusercontent.com/5925563/82321711-497eff00-99a3-11ea-8d77-73a524a496cb.png)

```
PHP Fatal error:
Uncaught TypeError: Argument 1 passed to Aws\Common\Client\AbstractClient::__construct() must be an instance of Aws\Common\Credentials\CredentialsInterface, array given,
* called in /home/user/public_html/wp-content/plugins/w3-total-cache/CdnEngine_Mirror_CloudFront.php on line 39 and
* defined in /home/user/public_html/wp-content/plugins/boldgrid-backup-premium/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php:73

Stack trace:
#0 /home/user/public_html/wp-content/plugins/w3-total-cache/CdnEngine_Mirror_CloudFront.php(39): Aws\Common\Client\AbstractClient->__construct(Array)
#1 /home/user/public_html/wp-content/plugins/w3-total-cache/CdnEngine_Mirror_CloudFront.php(199): W3TC\CdnEngine_Mirror_CloudFront->_init()
#2 /home/user/public_html/wp-content/plugins/w3-total-cache/Cdn_AdminActions.php(475): W3TC\CdnEngine_Mirror_CloudFront->create_container()
#3 /home/bradm/public_html/php-54/single-si in /home/user/public_html/wp-content/plugins/boldgrid-backup-premium/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php on line 73
```

**Comment by bwmarkle** [comment]
@jessecowens The fix for this is just about done, will be released soon.

Regarding the w3tc issue:

> A similar error occurred to another user using W3TC alongside another S3 plugin, if a fix can be found it should also be added to W3TC
> [08-May-2020 18:35:33 UTC] PHP Fatal error: Cannot redeclare Aws\constantly() (previously declared in /var/www/(snip)/wp-content/plugins/s3-media-maestro/vendor/aws/aws-sdk-php/src/functions.php:19) in /var/www/(snip)/wp-content/plugins/w3-total-cache/lib/Aws/Aws/functions.php on line 22

... I think I may have found the post you're referring to - https://wordpress.org/support/topic/conflict-with-s3-media-maestro/

... Marko provided a fix
> define('W3TC_SKIPLIB_AWS', true);
> This is not a solution but a way to make things work.
For the moment, this is what we may need to rely on. Please let me know if you hear more reports of this, or it doesn't actually work.
