### ISSUE TITLE
Nonce conflict

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-backup#332]
![image](https://user-images.githubusercontent.com/5925563/87179554-f3e11780-c2ac-11ea-957a-19d96c25d3b0.png)

**Comment by jessecowens** [comment]
For additional context, this issue has been reported in the [Support Center Forum](https://www.boldgrid.com/support/question/error-unable-to-upload-backup-file-invalid-nonce/) as well.
