### ISSUE TITLE
Design panels/internal navigation do not load in 1.9

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-backup#34]
**Describe the bug**
The 4 tabs (Backups/Settings/Preflight Check/Tools) work as expected but the navigation and the design panels in each tab are missing.

**To Reproduce**
1. Upload and Activate Backup 1.9rc
2. Enter Key
3. Dashboard > BG Backup > Settings > Settings
4. The navigation on the left isn't clickable and there's no design panels on the right
5. Same with 'Get Premium' notice on Backup tab and the 2 links on Tools

**Screenshots**
![no-panels](https://user-images.githubusercontent.com/20601160/54039718-a6710980-4191-11e9-95df-da2e5ec33a46.PNG)

**Comment by cssjoe** [comment]
Need to fix the library; revert "boldgrid-library-" back to "bglib-".
Find references using: `grep -RE 'boldgrid-library-(rating-prompt|collapsible-control|collapsible-open|ui-css|ui-js|sticky|license|attributes-js|attributes-css|misc-pub-section|)'`

**Comment by cssjoe** [comment]
Fixed by https://github.com/BoldGrid/library/commit/9e2957d9623be1287054b8a3bbf33bfbc6305dab
