### ISSUE TITLE
Feature: Explicit FTP over TLS

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/boldgrid-backup#36]
**Is your feature request related to a problem? Please describe.**
Servers that are set up to force High encryption requirements require modifications to class-boldgrid-backup-admin-ftp.php to work correctly.  All instances of 'ftp_connect' in the file need to be changed to 'ftp_ssl_connect' to work correctly.

**Describe the solution you'd like**
Having an option in the plugin settings would make this easier for users to configure.

**Comment by cssjoe** [comment]
# Testing Instructors
1. [ ] Configure FTPES.
1. [ ] Upload a backup to an FTP account.
1. [ ] Check the listing.
1. [ ] Delete the local backup
1. [ ] Check the listing.
1. [ ] Download the backup from FTP.
1. [ ] Check the listing.
1. [ ] Retest the steps above using standard FTP.
