### ISSUE TITLE
Timely auto updates are not delayed as expected

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-backup#403]
**Describe the bug**
Troubleshooting a Google Drive upload issue on a site using WP-Cron for scheduling, there also appear to be some problems with timely auto updates. Delay is set to 8 days, but all updates are run as soon as they are available instead of waiting the expected duration.

**Comment by bwmarkle** [comment]
@joe9663 can we close this ticket? I believe we found the issue to be something else?

**Comment by joe9663** [comment]
@bwmarkle closed. if it it happens again under different circumstances i'll just file a new one.
