### ISSUE TITLE
Files not restored with "bgbkup-cli.php restore method=ajax"

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-backup#41]
I deleted the readme, did the restore, and I did not have my readme back.
```
boldgrid-backup/cron$ ls -alh ../ |grep readme
-rw-r--r--   1 bradm bradm  17K Apr  2 13:59 readme.txt

boldgrid-backup/cron$ rm ../readme.txt 
rm: remove regular file â../readme.txtâ? y

boldgrid-backup/cron$ ls -alh ../ |grep readme

boldgrid-backup/cron$ php bgbkup-cli.php restore method=ajax
Starting restoration process...
Attempting to restore "http://domain.com/single-site-1" from backup archive file "/home/user/boldgrid_backup/boldgrid-backup-domain-12345678-20190402-174753.zip"...
Using Ajax URL address restoration process...
Success.

boldgrid-backup/cron$ ls -alh ../ |grep readme
```

Please see attached image.
![image](https://user-images.githubusercontent.com/5925563/55426392-b1317b00-5552-11e9-8f15-cda056798c42.png)

Other restore methods seem to work, just not ajax.

**Comment by cssjoe** [comment]
I cannot replicate this issue in version 1.10.4.

`[joec@lax-exe-dev-wpbex2 boldgrid-backup](dev)$ rm -f readme.txt`

`[joec@lax-exe-dev-wpbex2 boldgrid-backup](dev)$ php cli/bgbkup-cli.php restore method=ajax
Starting restoration process...
Attempting to restore "https://wpbex2-dev-joec.boldgrid.com" from backup archive file "/home/joec/boldgrid_backup/boldgrid-backup-wpbex2-dev-joec.boldgrid.com-5665aa58-20190730-163445.zip"...
Using Ajax URL address restoration process...
Success.`

`[joec@lax-exe-dev-wpbex2 boldgrid-backup](dev)$ ls -l|grep readme
-rw-r--r--   1 joec joec  23168 Jul 30 12:38 readme.txt`
