### ISSUE TITLE
Information Disclosulre Server Information (Unauthenticated)

### ISSUE THREAD

**Issue by blackcon** [BoldGrid/boldgrid-backup#426]
**Describe the bug**
- I have a WordPress 5.6 site running under PHP 7.0.33. If you request to the `env-info.php` file that exists when you install the plug-in(boldgrid-backup latest version), you can get the information on that server without permission.
- This information will provide information for hacking into the server. When requesting env-info.php, a verification logic is required.
> [root@bk-wordpress boldgrid-backup]# php -v
PHP 7.0.33 (cli) (built: Sep 29 2020 10:34:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33, Copyright (c) 1999-2017, by Zend Technologies

> [root@bk-wordpress boldgrid-backup]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
...

> [root@bk-wordpress boldgrid-backup]# head readme.txt
=== Total Upkeep – WordPress Backup Plugin plus Restore & Migrate by BoldGrid ===
Contributors: boldgrid, joemoto, imh_brad, rramo012, bgnicolepaschen, jamesros161
Tags: backup, cloud backup, database backup, restore, wordpress backup
Requires at least: 4.4
Tested up to: 5.6
Requires PHP: 5.4
Stable tag: 1.14.9
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html

**To Reproduce**
1. Install plug-in boldgrid-backup
2. request URL
: domain.com/wordpress/wp-content/plugins/boldgrid-backup/cli/env-info.php
3. get server information
: gateway_interface, http_host, php_sapi_name, php_uname, php_version, server_addr, server_name, server_protocol, server_software, uid, username

**Expected behavior**
you can get server informations
: gateway_interface, http_host, php_sapi_name, php_uname, php_version, server_addr, server_name, server_protocol, server_software, uid, username

**Screenshots**
![image](https://user-images.githubusercontent.com/6852711/102108050-c446c480-3e75-11eb-9149-4609581c85b1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : chrome
 - Version :  87.0.4280.88

**Comment by bwmarkle** [comment]
Hi @blackcon - thank you for submitting this very detailed issue! We're looking into it, and will get back to you soon.
