### ISSUE TITLE
[Bug] Conflict with S3 Media Vault

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-backup#452]
When Total Upkeep Premium is installed together with the [S3 Media Vault](https://s3mediavault.com) plugin, the AWS clients conflict.
```
Error Details
=============
An error of type E_ERROR was caused in line 73 of the file /home/u802513104/domains/learn.jdmis.edu.sg/public_html/wp-content/plugins/boldgrid-backup-premium/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php. Error message: Uncaught TypeError: Argument 1 passed to Aws\Common\Client\AbstractClient::__construct() must be an instance of Aws\Common\Credentials\CredentialsInterface, array given, called in /home/u802513104/domains/learn.jdmis.edu.sg/public_html/wp-content/plugins/S3MediaVaultPro/vendor/aws/aws-sdk-php/src/MultiRegionClient.php on line 53 and defined in /home/u802513104/domains/learn.jdmis.edu.sg/public_html/wp-content/plugins/boldgrid-backup-premium/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php:73
```
[Original forum topic](https://www.boldgrid.com/support/question/boldgrid-premium-amazon-s3-conflict-argument-1-passed-to-awscommonclientabstractclient__construct-must-be-an-instance-of-awscommoncredentialscredentialsinterface-array-given/).

**Comment by bwmarkle** [comment]
Hi @RaviJayagopal,

In response to your question [here](https://www.boldgrid.com/support/question/boldgrid-premium-amazon-s3-conflict-argument-1-passed-to-awscommonclientabstractclient__construct-must-be-an-instance-of-awscommoncredentialscredentialsinterface-array-given/):

In vendor\guzzlehttp\guzzle\src\ClientInterface.php we have:
```
/**
 * Client interface for sending HTTP requests
 */
interface ClientInterface extends HasEmitterInterface
{
    const VERSION = '5.3.1';
```

It looks like both plugins are including the aws-sdk-php library:
* plugins/S3MediaVaultPro/vendor/aws/aws-sdk-php/
* plugins/boldgrid-backup-premium/vendor/aws/aws-sdk-php/

We are running aws/aws-sdk-php version 2.8.31. Which version are you running?

```
    "packages": [
        {
            "name": "aws/aws-sdk-php",
            "version": "2.8.31",
            "source": {
                "type": "git",
                "url": "https://github.com/aws/aws-sdk-php.git",
                "reference": "64fa4b07f056e338a5f0f29eece75babaa83af68"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/aws/aws-sdk-php/zipball/64fa4b07f056e338a5f0f29eece75babaa83af68",
                "reference": "64fa4b07f056e338a5f0f29eece75babaa83af68",
                "shasum": ""
            },
            "require": {
                "guzzle/guzzle": "~3.7",
                "php": ">=5.3.3"
            },
```

Thanks,
\- Brad
