### ISSUE TITLE
Feature: Add PHP.ini information to preflight check screen

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/boldgrid-backup#46]
**Describe the solution you'd like**
Add relevant PHP settings such as memory limit, max upload size, PHP version, max exec time to pre-flight check screen for diagnostic purposes.

**Comment by cssjoe** [comment]
The information is included in WordPress 5.2 ("/wp-admin/site-health.php?tab=debug").  We decided not to include features that will be in current or near-future releases of WordPress.
![wp52-server-info-example](https://user-images.githubusercontent.com/11447263/56968179-adcce780-6b30-11e9-8929-e4cfd9506325.jpg)
