### ISSUE TITLE
[Feature] Add /wp-content/cache to default exclusion rules

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-backup#486]
**Is your feature request related to a problem? Please describe.**
Some websites encounter issues generating backups when /wp-content/cache is included in the backup archive. This problem was witnessed specifically with W3TC implemented, but it is likely that other caching plugins could create similar issues.

**Comment by jessecowens** [comment]
+1 from [customer feedback in the internal slack](https://inmotionhosting.slack.com/archives/C6QSWR10D/p1697746977644989)
