### ISSUE TITLE
Cannot close ZIP archive file /home/user/backup.zip

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-backup#51]
```
Apr 17 12:40:34 HOST httpd: PHP Warning:
fileperms(): stat failed for /home/user/wp-content/cache/object/d55/fe7/d55fe78a03bc8e7134d98538818a0ef7.php in
/home/user/wp-content/plugins/boldgrid-backup/admin/compressor/class-boldgrid-backup-admin-compressor-php-zip.php on line 160

Apr 17 12:41:44 HOST httpd: PHP Warning:
ZipArchive::close(): Read error: No such file or directory in
/home/user/wp-content/plugins/boldgrid-backup/admin/compressor/class-boldgrid-backup-admin-compressor-php-zip.php on line 207
```

**Comment by bwmarkle** [comment]
# Testing Instructors
1. [ ] Pick a file and **chmod 000** it.
1. [ ] Create a backup, and ensure the 000'd file is in that backup.
1. [ ] When the new backup has finished, manually review the .log file for it. You should see a "backup_errors" section, and an error similar to:
> Permission defined. Unable to add the following file to your backup: /home/user/public_html/wp-content/plugins/boldgrid-backup/yarn.lock

**Comment by bwmarkle** [comment]
This ticket introduces the ability to have errors on the log. They will need to be shown in the future. Ticket #55 created to handle that.

**Comment by cssjoe** [comment]
Tests ok.  Just fix the2  minor phpcs violations.
