### ISSUE TITLE
Restorations with different permalinks

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-backup#524]
So here's what I've figured out regarding flushing rewrite after restoration.

If the origin site and the destination site have a different permalink structure, the rewrite rules need to be flushed. We're doing it with wp-cli, and you're doing it within total upkeep after the backup is restored... but we're still seeing an issue.

The problem is that we're flushing the rewrite rules, but the permalink structure is the same as what's stored in the database. What actually works is setting the permalink structure to anything else. I'm guessing there's a conditional in WP that prevents the flush from triggering if: cached rules = db rules or something like that.

What doesn't work:
* wp rewrite flush
* wp rewrite flush --hard

What does work:
* wp rewrite structure '/%postname%/'
* Changeing the permalinks structure in the UI

The issue can be tested by checking the link response header when making a request to the Wordpress site. I've updated wordpress central to use `wp rewrite structure '/%postname%/'` which is not desirable because it changes the users permalink structure. Can you run some more tests by making sure the rewrite rules are different on the 2 sites, origin site using postname and destination using plain. Then after the transfer, check the destination sites location header to make sure it's using the postname structure.

But basically, whatever permalink structure the origin site has, the destination site should have it as well.

**Comment by joe9663** [comment]
@bwmarkle Looks like we can replicate the bug regularly. Tested the issue migrating between two Cloud WordPress installations. Bug also occurs within a single installation when restoring a backup with a different Permalink structure.

### Replication (2 Sites)
1. Create two installations with separate Permalink structures, one using Plain the other with Postname.
2. Create a backup of the Postname install and migrate it to the Plain one.
3. Restore the Postname backup on Plain.
4. Attempt to access one of the subpages to generate a 404.

### Replication (1 Site)
1. Set Permalinks structure to Postname and create a backup.
2. Change Permalinks to use Plain.
3. Restore the backup.
4. Subpages will 404 following the restoration.
