### ISSUE TITLE
What's triggering backup? Issue collecting information for very large backup log

### ISSUE THREAD

**Issue by SitesByYogi** [BoldGrid/boldgrid-backup#586]
User: https://www.boldgrid.com/support/question/multiple-backups-triggered/?view=all#post-129477

I have the scheduler turned off for back ups. I saw the disk space usage on my site jump yesterday. When I went to check what was going on, I found that total upkeep had created five backups a hour apart. What would cause it to do this? The last one was yesterday at 9:25 AM.

No data is shown in "more info" section of "view details" section of backup.  Backup log itself appears to be timing out so there is no way to find what triggering the backup.

Problem is backups are 4.3GB+ and php is having a problem getting the log out of the backup to get all information associated with it. That explains why there’s no extra info in the space usually shown in “more info”.

Solution: 
We just need to add a line here to write to the log what the trigger was. Can you create the ticket and submit the PR?

![Screenshot from 2024-04-15 13-53-44](https://github.com/BoldGrid/boldgrid-backup/assets/90996605/3b2184e0-aaf6-4536-aaee-55d8f4967d30)

**Comment by codifycreative** [comment]
I too am having this problem across several websites.  I only have weekly backups configured, but for the last week each site is backing up 4-5 times per day.
