### ISSUE TITLE
Add an FTP setting for passive mode.

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-backup#59]
FTPES is currently taking a bit longer than FTP, example:

```
The "Backup Archives" page is taking much longer to load.

FTPES
24s
22s
23s

FTP
7s
7s
9s
```

Adding a passive / auto detect option would help speed things up.

**Comment by cssjoe** [comment]
I was going to add "Auto/Active/Passive" in the FTP settings.  It would run the test (in auto) and set it to either active or passive.
