### ISSUE TITLE
Constant FTP Connections in plugin pages

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/boldgrid-backup#9]
**Description**
Plugin attempts to make an FTP connection with every page load within the plugin.  Viewing Settings, Tools, Preflight Check, or any of the other settings causes the plugin to attempt an FTP login.

When FTP option is setup user has to wait for the connection to timeout before the plugin page loads, and requires killing the processes server side to bypass waiting for the connection to timeout.

**Comment by bwmarkle** [comment]
Testing instructions:

1. Setup ftp within the backup plugin
1. Access the settings pages of the boldgrid backup plugin 3 or 4 times. The first time, it may login to your ftp server, but subsequent visits to the settings page should not log in to your ftp server.

How do you know if your ftp server is being logged into? Either review the logs from the command line or do something like this: https://gist.github.com/bwmarkle/adf029731c176e10f01627b73d43d736
